# Generated by Django 6.0.2 on 2026-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippet_author_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='happiness_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
