# Generated by Django 6.0.2 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_snippet_happiness_score_snippet_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='happiness_score',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='employee_name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
