# Generated by Django 6.0.2 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employmentstatus_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name': 'Ekip Durumu', 'verbose_name_plural': 'Ekip Durumları'},
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyon'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='current_work',
            field=models.TextField(verbose_name='Şu Anki Görev'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='employee_name',
            field=models.CharField(max_length=100, verbose_name='Çalışan İsmi'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='status_type',
            field=models.CharField(choices=[('available', 'Müsait'), ('busy', 'Meşgul')], default='available', max_length=20, verbose_name='Durum'),
        ),
    ]
