# Generated by Django 6.0.2 on 2026-02-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employmentstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentstatus',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışan İsmi'),
        ),
    ]
