# Generated by Django 6.0.2 on 2026-03-11 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_id_alter_employmentstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='experience_rating',
            field=models.IntegerField(default=5, help_text='1-5 arasında bir puan veriniz.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
