# Generated by Django 5.2.7 on 2026-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_comment_id_alter_employmentstatus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic')], default='en', max_length=10),
        ),
    ]
