# Generated by Django 5.2.7 on 2026-04-13 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_normalize_snippet_turkish_dotted_i'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('vendor', models.CharField(max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=160)),
                ('license_mode', models.CharField(choices=[('shared', 'Shared Team License'), ('assigned', 'Assigned User License')], default='assigned', max_length=20)),
                ('provider_code', models.CharField(choices=[('manual', 'Manual'), ('cursor', 'Cursor'), ('adobe', 'Adobe'), ('figma', 'Figma'), ('other', 'Other')], default='manual', max_length=20)),
                ('record_source', models.CharField(choices=[('manual', 'Manual'), ('provider_sync', 'Provider Sync')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_workspace_id', models.CharField(blank=True, max_length=255)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('seats_total', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_software_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software Asset',
                'verbose_name_plural': 'Software Assets',
                'ordering': ['renewal_date', 'name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_at', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.softwareasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_asset_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software Asset Assignment',
                'verbose_name_plural': 'Software Asset Assignments',
                'ordering': ['-is_active', 'assigned_at', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'user'), name='unique_software_asset_assignment')],
            },
        ),
    ]
