# Generated by Django 6.0.2 on 2026-04-13 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_softwareasset_softwareassetassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_software_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='contract_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='cost_center',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='documentation_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='extra_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='is_scim_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='is_sso_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_software_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='record_type',
            field=models.CharField(choices=[('saas', 'SaaS Subscription'), ('desktop_license', 'Desktop License'), ('team_tool', 'Team Tool'), ('single_user_license', 'Single User License'), ('api_subscription', 'API Subscription'), ('support_service', 'Support Service')], default='saas', max_length=30),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='renewal_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_software_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='support_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='vendor_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='provider_code',
            field=models.CharField(choices=[('manual', 'Manual'), ('cursor', 'Cursor'), ('adobe', 'Adobe'), ('figma', 'Figma'), ('github', 'GitHub'), ('microsoft', 'Microsoft 365'), ('openai', 'OpenAI'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('message', 'Message'), ('comment', 'Comment'), ('snippet', 'Snippet'), ('license', 'License'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_product', models.CharField(max_length=160)),
                ('provider_code', models.CharField(choices=[('manual', 'Manual'), ('cursor', 'Cursor'), ('adobe', 'Adobe'), ('figma', 'Figma'), ('github', 'GitHub'), ('microsoft', 'Microsoft 365'), ('openai', 'OpenAI'), ('other', 'Other')], default='other', max_length=20)),
                ('request_type', models.CharField(choices=[('access_request', 'Access Request'), ('new_purchase', 'New Purchase'), ('seat_increase', 'Seat Increase'), ('replacement', 'Replacement')], default='access_request', max_length=30)),
                ('preferred_plan', models.CharField(blank=True, max_length=160)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('cost_center', models.CharField(blank=True, max_length=120)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_requests', to='api.softwareasset')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_license_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Request',
                'verbose_name_plural': 'License Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('imported', 'Imported'), ('assignment_changed', 'Assignment Changed'), ('reclaimed', 'Reclaimed'), ('sync_requested', 'Sync Requested'), ('sync_result', 'Sync Result'), ('request_created', 'Request Created'), ('request_status_changed', 'Request Status Changed')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_asset_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.softwareasset')),
            ],
            options={
                'verbose_name': 'Software Asset Audit Log',
                'verbose_name_plural': 'Software Asset Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssetSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(choices=[('manual', 'Manual'), ('cursor', 'Cursor'), ('adobe', 'Adobe'), ('figma', 'Figma'), ('github', 'GitHub'), ('microsoft', 'Microsoft 365'), ('openai', 'OpenAI'), ('other', 'Other')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error')], default='pending', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='api.softwareasset')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_asset_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software Asset Sync Log',
                'verbose_name_plural': 'Software Asset Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
