# Generated by Django 5.2.7 on 2026-04-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_aicoderequest_aicodevalidationresult_githubaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubCommitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=120)),
                ('author_login', models.CharField(blank=True, max_length=120)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('message_title', models.CharField(blank=True, max_length=255)),
                ('message_body', models.TextField(blank=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changed_files_count', models.PositiveIntegerField(default=0)),
                ('commit_url', models.URLField(blank=True, max_length=500)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('is_merge_commit', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_activities', to='api.githubrepository')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit_activities', to='api.repositoryscan')),
            ],
            options={
                'verbose_name': 'GitHub Commit Activity',
                'verbose_name_plural': 'GitHub Commit Activities',
                'ordering': ['-committed_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'sha'), name='unique_commit_sha_per_repository')],
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_login', models.CharField(blank=True, max_length=120)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('pull_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(default='open', max_length=30)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_merged', models.BooleanField(default=False)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changed_files_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('review_comments_count', models.PositiveIntegerField(default=0)),
                ('commit_count', models.PositiveIntegerField(default=0)),
                ('html_url', models.URLField(blank=True, max_length=500)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_activities', to='api.githubrepository')),
            ],
            options={
                'verbose_name': 'GitHub Pull Request Activity',
                'verbose_name_plural': 'GitHub Pull Request Activities',
                'ordering': ['-opened_at', '-last_synced_at'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'pull_number'), name='unique_pull_number_per_repository')],
            },
        ),
    ]
